### ISSUE TITLE
Add support for inner-class Visitor interfaces

### ISSUE THREAD

**Issue by jbgi** [sviperll/adt4j#11]
on my wish list :)

**Comment by sviperll** [comment]
The limitation is that you can't generate inner class from annotation processor. Visitors declared as inner-classes can be processed, but outer-level class will be generated for each inner-class visitor.

I have intentionally left this feature out as the connection between visitor-interface and value-class becomes too obscure... Do you think that it's worth it?

**Comment by jbgi** [comment]
The use case is when you manually extends the generated value class.
In this case I would like that the Visitor interface be an inner class of the extending class.
An example of what I want:
```java
public final class List<T> extends BaseList<T> {

   ...

   @GenerateValueClassForVisitor(resultVariableName = "R", valueClassName = "BaseList")
   public interface Cases<T, R> {
      R nil();
      R list(T head, List<T> tail);
  }

  public <R> R match(Cases<T, R> cases) {
      return super.accept(cases);
  }
  ...
}
```
Ideally I would also be able to customize the accept method name through the annotation.

**Comment by sviperll** [comment]
You still can't do this because of circular dependencies.

See [this commit](https://github.com/sviperll/adt4j/commit/5cc97e4c4c59885ab930e7ab255f2de0c0afe21d).

There is working example as close to yours as I see possible:

 * [BaseFancyListCases.java](https://github.com/sviperll/adt4j/blob/5cc97e4c4c59885ab930e7ab255f2de0c0afe21d/adt4j-examples/src/main/java/com/github/sviperll/adt4j/examples/BaseFancyListCases.java)
 * [FancyList.java](https://github.com/sviperll/adt4j/blob/5cc97e4c4c59885ab930e7ab255f2de0c0afe21d/adt4j-examples/src/main/java/com/github/sviperll/adt4j/examples/FancyList.java)

**Comment by jbgi** [comment]
I see, yes I forgot the circular dependencies. Thank-you for spending the time to analyse this issue.
Maybe for this use case what I ultimately need is a generator of "typeclass" instances (of Show, Eq, Hash), which I could then use in my List implementation.

**Comment by sviperll** [comment]
You can do what you want with open recursion. See:

 * [BaseFancyListCases.java](https://github.com/sviperll/adt4j/blob/117e164b20d49bd245396b495c14e22a938adf04/adt4j-examples/src/main/java/com/github/sviperll/adt4j/examples/BaseFancyListCases.java)
 * [FancyList.java](https://github.com/sviperll/adt4j/blob/117e164b20d49bd245396b495c14e22a938adf04/adt4j-examples/src/main/java/com/github/sviperll/adt4j/examples/FancyList.java)

**Comment by jbgi** [comment]
Yes this is what I want.
If BaseFancyListCases could be an inner (package-private) interface that would be perfect.

**Comment by sviperll** [comment]
In my example BaseFancyListCases is package private interface. FancyList provides public inner interface Cases as part of it's public API to use in it's "match" method. It's full working example with current version of adt4j.

BaseFancyListCases can be innter-interface, but it's enclosing class should be some class other than FancyList. Otherwise this will create unresolvable for adt4j circular dependency.

**Comment by sviperll** [comment]
@jbgi, does open-recursion version fits your needs?

**Comment by jbgi** [comment]
yes. thank-you!

**Comment by sviperll** [comment]
Inner classes should work now.

**Comment by jbgi** [comment]
Works great!
