### ISSUE TITLE
Use JavaPoet instead of JCodeModel?

### ISSUE THREAD

**Issue by jbgi** [sviperll/adt4j#19]
I find JavaPoet - https://github.com/square/javapoet - API (much) easier, it is much more popular. I suspect using it in adt4j could simplify a great deal of code and should make life easier for external contributors (like me ;-).
The only problem is that it require jdk 7. but now that even jdk7 is no more publicly supported by Oracle, I think it could be the right time to left out jdk6 support in a next major release or so.
What do you think? // cc @talios

**Comment by sviperll** [comment]
I'm all for ditching Java 6 support :)

I think that JavaPoet API seems easy because it provides less than jcodemodel.

Currenly jcodemodel implements two functions:

 * Java source code generation
 * Provides meta-language to analyze existing code

JavaPoet can only support Java code generation. If we replace jcodemodel with JavaPoet, we will have to use JavaPoet for code generation and javax.mirror API as a meta-language. Two APIs are more complex than one. Original choice of jcodemodel was almost completely justified by the fact that it can be forced to serve both these purposes.

Comparing jcodemodel with JavaPoet in aspect of code generation, jcodemodel seems slightly better as it doesn't rely on string concatenation which prevents some class of errors.

**Comment by jbgi** [comment]
I see. Thanks for the explanation.

**Comment by talios** [comment]
@jbgi javapoet for the win! I've usually used the precursor to JavaPoet and its MUCH nicer for generation.

As far as the javax.mirror stuff, I know the AutoValue project from Google has some nice abstractions for dealing with the mirrors in a clean way. Not sure if that's in a separate artifact tho.

I was tempted to suggest it awhile ago, but that's an epic change.  Interestingly, Immutables.org use a javascript based template writer I believe.

**Comment by sviperll** [comment]
I'll close this issue for now, as I think JavaPoet-rewrite is not realistic in new future...
